import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  site: 'https://frasto.freightpx.com',
  vite: {
    plugins: [tailwindcss()],
  },
  integrations: [
    starlight({
      title: 'Frasto UI',
      description: 'An Astro-first design system for serious SaaS applications.',
      favicon: '/favicon.ico',
      logo: {
        dark: '../../logo/frastro_logo_white_nobg.png',
        light: '../../logo/frastro_logo_black_nobg.png',
        alt: '',
        replacesTitle: false,
      },
      customCss: ['./src/styles/custom.css'],
      lastUpdated: true,
      editLink: {
        baseUrl: 'https://github.com/Freightpx/frasto/edit/main/apps/web/',
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/Freightpx/frasto',
        },
      ],
      sidebar: [
        {
          label: 'Introduction',
          items: [
            { label: 'Overview', slug: 'docs/getting-started/introduction' },
            { label: 'Why Frasto', slug: 'docs/getting-started/why-frasto' },
            { label: 'Product principles', slug: 'docs/getting-started/principles' },
            { label: 'Architecture overview', slug: 'docs/getting-started/architecture' },
            { label: 'Project status', slug: 'docs/getting-started/status' },
            { label: 'Roadmap', slug: 'docs/getting-started/roadmap' },
          ],
        },
        {
          label: 'Getting Started',
          items: [
            { label: 'Installation', slug: 'docs/getting-started/installation' },
            { label: 'Quick start', slug: 'docs/getting-started/quick-start' },
            { label: 'Project setup', slug: 'docs/getting-started/project-setup' },
            { label: 'Styles', slug: 'docs/getting-started/styles' },
            { label: 'Themes', slug: 'docs/getting-started/themes' },
            { label: 'Icons', slug: 'docs/getting-started/icons' },
            { label: 'TypeScript', slug: 'docs/getting-started/typescript' },
          ],
        },
        {
          label: 'Foundations',
          items: [
            { label: 'Design principles', slug: 'docs/foundations/design-principles' },
            { label: 'Color', slug: 'docs/foundations/color' },
            { label: 'Typography', slug: 'docs/foundations/typography' },
            { label: 'Spacing', slug: 'docs/foundations/spacing-layout' },
            { label: 'Shape & depth overview', slug: 'docs/foundations/shape-depth' },
            { label: 'Radius', slug: 'docs/foundations/radius' },
            { label: 'Borders', slug: 'docs/foundations/borders' },
            { label: 'Shadows', slug: 'docs/foundations/shadows' },
            { label: 'Layout & grid', slug: 'docs/foundations/layout' },
            { label: 'Responsive design', slug: 'docs/foundations/responsive-design' },
            { label: 'Motion', slug: 'docs/foundations/motion' },
            { label: 'Accessibility', slug: 'docs/foundations/accessibility' },
            { label: 'Themes', slug: 'docs/foundations/themes' },
            { label: 'Dark mode', slug: 'docs/foundations/dark-mode' },
            { label: 'Iconography', slug: 'docs/foundations/iconography' },
            { label: 'Content & copy', slug: 'docs/foundations/content-copy' },
          ],
        },
        {
          label: 'Architecture',
          items: [
            { label: 'Astro first', slug: 'docs/architecture/astro-first' },
            { label: 'Server-first', slug: 'docs/architecture/server-first' },
            { label: 'Progressive interactivity', slug: 'docs/architecture/progressive-interactivity' },
            { label: 'CSS & token architecture', slug: 'docs/architecture/css-tokens' },
            { label: 'Web Components policy', slug: 'docs/architecture/web-components' },
            { label: 'Dependency policy', slug: 'docs/architecture/dependencies' },
            { label: 'Component philosophy', slug: 'docs/architecture/component-philosophy' },
            { label: 'Component API conventions', slug: 'docs/architecture/component-api' },
            { label: 'TypeScript conventions', slug: 'docs/architecture/typescript' },
            { label: 'Data contracts', slug: 'docs/architecture/data-contracts' },
            { label: 'Backend independence', slug: 'docs/architecture/backend-agnostic' },
            { label: 'Theming contract', slug: 'docs/architecture/theming' },
          ],
        },
        {
          label: 'Core Components',
          items: [
            { label: 'Overview', slug: 'docs/components/overview' },
            { label: 'Status & roadmap', slug: 'docs/components/roadmap' },
            { label: 'Button', slug: 'docs/components/button' },
            { label: 'IconButton', slug: 'docs/components/icon-button' },
            { label: 'Input', slug: 'docs/components/input' },
            { label: 'Textarea', slug: 'docs/components/textarea' },
            { label: 'Checkbox', slug: 'docs/components/checkbox' },
            { label: 'Radio', slug: 'docs/components/radio' },
            { label: 'Switch', slug: 'docs/components/switch' },
            { label: 'Badge', slug: 'docs/components/badge' },
            { label: 'Avatar', slug: 'docs/components/avatar' },
            { label: 'Separator', slug: 'docs/components/separator' },
            { label: 'Surface', slug: 'docs/components/surface' },
            { label: 'Skeleton', slug: 'docs/components/skeleton' },
            { label: 'Spinner', slug: 'docs/components/spinner' },
            { label: 'Tooltip', slug: 'docs/components/tooltip' },
            { label: 'Select', slug: 'docs/components/select' },
            { label: 'Dropdown', slug: 'docs/components/dropdown' },
            { label: 'Dialog', slug: 'docs/components/dialog' },
            { label: 'Drawer', slug: 'docs/components/drawer' },
            { label: 'Popover', slug: 'docs/components/popover' },
            { label: 'Tabs', slug: 'docs/components/tabs' },
            { label: 'Actions', slug: 'docs/components/actions' },
            { label: 'Forms', slug: 'docs/components/forms' },
            { label: 'Display', slug: 'docs/components/display' },
            { label: 'Containers', slug: 'docs/components/containers' },
            { label: 'Navigation', slug: 'docs/components/navigation' },
            { label: 'Overlays', slug: 'docs/components/overlays' },
            { label: 'Feedback', slug: 'docs/components/feedback' },
          ],
        },
        {
          label: 'Application Components',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'docs/application-components/overview' },
            { label: 'AppShell', slug: 'docs/application-components/app-shell' },
            { label: 'Sidebar', slug: 'docs/application-components/sidebar' },
            { label: 'PageHeader', slug: 'docs/application-components/page-header' },
            { label: 'Stat', slug: 'docs/application-components/stat' },
            { label: 'SearchInput', slug: 'docs/application-components/search-input' },
            { label: 'ResourceTable', slug: 'docs/application-components/resource-table' },
            { label: 'FilterBar', slug: 'docs/application-components/filter-bar' },
            { label: 'Pagination', slug: 'docs/application-components/pagination' },
            { label: 'EmptyState', slug: 'docs/application-components/empty-state' },
            { label: 'DetailLayout', slug: 'docs/application-components/detail-layout' },
            { label: 'SettingsLayout', slug: 'docs/application-components/settings-layout' },
            { label: 'ActivityFeed', slug: 'docs/application-components/activity-feed' },
          ],
        },
        {
          label: 'Patterns',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'docs/patterns/overview' },
            { label: 'App shell', slug: 'docs/patterns/app-shell' },
            { label: 'Dashboard', slug: 'docs/patterns/dashboard' },
            { label: 'Resource list', slug: 'docs/patterns/resource-list' },
            { label: 'Resource detail', slug: 'docs/patterns/resource-detail' },
            { label: 'Settings', slug: 'docs/patterns/settings' },
            { label: 'Master / detail', slug: 'docs/patterns/master-detail' },
            { label: 'CRUD', slug: 'docs/patterns/crud' },
            { label: 'Filtering', slug: 'docs/patterns/filtering' },
            { label: 'Bulk actions', slug: 'docs/patterns/bulk-actions' },
            { label: 'Loading states', slug: 'docs/patterns/loading-states' },
            { label: 'Empty states', slug: 'docs/patterns/empty-states' },
            { label: 'Error states', slug: 'docs/patterns/error-states' },
          ],
        },
        {
          label: 'Recipes',
          items: [
            { label: 'Overview', slug: 'docs/recipes/overview' },
            { label: 'Acme Cloud', slug: 'docs/recipes/acme-cloud' },
          ],
        },
        {
          label: 'Guides',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'docs/guides/overview' },
            { label: 'Build a dashboard', slug: 'docs/guides/dashboard' },
            { label: 'Build a CRM', slug: 'docs/guides/crm' },
            { label: 'Build settings', slug: 'docs/guides/settings' },
            { label: 'Tables & data states', slug: 'docs/guides/tables' },
            { label: 'Forms', slug: 'docs/guides/forms' },
            { label: 'Responsive layouts', slug: 'docs/guides/responsive-layouts' },
            { label: 'Backend integrations', slug: 'docs/guides/backend-integrations' },
          ],
        },
        {
          label: 'Contributing',
          items: [
            { label: 'Overview', slug: 'docs/contributing/overview' },
            { label: 'Component proposals', slug: 'docs/contributing/component-proposals' },
            { label: 'Documentation', slug: 'docs/contributing/documentation' },
            { label: 'Governance', slug: 'docs/contributing/governance' },
          ],
        },
      ],
    }),
  ],
});
